audio:
  channels: 1
  input_device: null
  output_device: null
  sample_rate: 16000
feedback:
  apply_adjustments: true
  cooldown: 5
  enabled: true
  frequency: 0.3
intent:
  debug_mode: false
  enabled: true
llm:
  max_tokens: 256
  model_name: gemma:2b
  system_prompt_file: config/prompts/system.txt
  temperature: 0.7
  tool_prompt_file: config/prompts/tools.txt
logging:
  backup_count: 5
  file: data/logs/coda.log
  level: INFO
  max_size: 10485760
memory:
  auto_persist: true
  chunk_overlap: 50
  chunk_size: 150
  device: cpu
  embedding_model: all-MiniLM-L6-v2
  export_dir: data/memory
  long_term_enabled: true
  long_term_path: data/memory/long_term
  max_memories: 1000
  max_tokens: 800
  max_turns: 20
  min_chunk_length: 50
  persist_interval: 1
  vector_db: chroma
  # Memory snapshot settings
  snapshot_dir: data/memory/snapshots
  auto_snapshot: true
  snapshot_interval: 10
  # Temporal weighting settings
  default_decay_rate: 30.0  # Half-life in days for default memory decay
  # Decay rates for different memory types (half-life in days)
  conversation_decay_rate: 15.0  # Conversations decay faster
  fact_decay_rate: 60.0  # Facts decay slower
  preference_decay_rate: 90.0  # Preferences decay very slowly
  feedback_decay_rate: 45.0  # Feedback decays moderately
  summary_decay_rate: 30.0  # Summaries decay at default rate
  # Recency bias factor (higher = more bias towards recent memories)
  recency_bias: 1.0
  # Importance retention factor (higher = importance decays slower)
  importance_retention: 0.8
  # Reinforcement settings
  reinforcement_boost: 0.2  # How much reinforcement boosts importance
  max_reinforcement_count: 5  # Maximum number of reinforcements
personality:
  lore_file: config/personality/personal_lore.json
  use_advanced: true
stt:
  compute_type: float32
  device: cpu
  language: null
  model_size: base
  vad_filter: true
tools:
  available:
  - get_time
  - tell_joke
  - get_weather
  - get_date
  - get_memory_stats
  - search_memories
  - add_fact
  - add_preference
  enabled: true
tts:
  audio_prompt_path: null
  cfg_scale: 3.0
  device: cuda
  elevenlabs_api_key: sk_7b576d29574b14a97150b864497d937c4e1fdd2d6b3a1e4d
  elevenlabs_model_id: eleven_multilingual_v2
  elevenlabs_similarity_boost: 0.75
  elevenlabs_stability: 0.5
  elevenlabs_style: 0.0
  elevenlabs_use_speaker_boost: true
  elevenlabs_voice_id: kdmDKE6EkgrWrrykO9Qt
  engine: elevenlabs
  language: EN
  speed: 1.0
  temperature: 1.3
  top_p: 0.95
  use_torch_compile: true
  voice: EN-Default
