# Coda Lite Configuration

# Speech-to-Text settings
stt:
  model_size: "base"  # Options: tiny, base, small, medium, large
  language: "en"
  device: "cuda"  # Options: cpu, cuda - Using GPU for faster transcription
  compute_type: "float16"  # Options: float32, float16, int8 - float16 is faster on GPU

# Language Model settings
llm:
  model_name: "llama3"
  temperature: 0.7
  max_tokens: 256
  system_prompt_file: "config/prompts/system.txt"
  tool_prompt_file: "config/prompts/tools.txt"

# Text-to-Speech settings
tts:
  engine: "csm"  # Options: csm
  language: "EN"  # Language code for CSM-1B (EN, ES, FR, ZH, JP, KR)
  voice: "EN-Default"  # Available voices for English: EN-US, EN-BR, EN_INDIA, EN-AU, EN-Default
  speed: 1.0
  device: "cuda"  # Options: cpu, cuda - Using GPU for better performance

# Audio settings
audio:
  input_device: null  # null = default device
  output_device: null  # null = default device
  sample_rate: 16000
  channels: 1

# Tool settings
tools:
  enabled: true
  available:
    - get_time
    - tell_joke
    - get_weather

# Logging settings
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "data/logs/coda.log"
  max_size: 10485760  # 10 MB
  backup_count: 5
